--Create database Babel ;
Create table CLIENTES(
		IDCLIENTE INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		NOMBRE VARCHAR(50),
		APPATERNO VARCHAR(50),
		APMATERNO VARCHAR(50),
		BORRADO BIT,
		FECHAMOD TIMESTAMP
		);
CREATE TABLE PLANES (
		IDPLAN INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		DESCRIPCION VARCHAR(50),
		FECHAMOD TIMESTAMP
);

CREATE TABLE COBERTURA (
		IDCOBERTURA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		DESCRIPCION VARCHAR(50),
		FECHAMOD TIMESTAMP
);

CREATE TABLE REL_CLIENTE_PLAN(
	IDCP INT  IDENTITY(1,1) NOT NULL PRIMARY KEY,
	IDCLIENTE INT NOT NULL  FOREIGN KEY REFERENCES CLIENTES(IDCLIENTE),
	IDPLAN INT NOT NULL  FOREIGN KEY REFERENCES PLANES(IDPLAN)
);


CREATE TABLE REL_PLAN_COBER(
	IDpc INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	IDPLAN INT NOT NULL  FOREIGN KEY REFERENCES PLANES(IDPLAN),
	IDCOBER INT NOT NULL  FOREIGN KEY REFERENCES COBERTURA(IDCOBERTURA)
);

