--Create database Babel ;
Create table CLIENTES(
		IDCLIENTE INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		NOMBRE VARCHAR(50),
		APPATERNO VARCHAR(50),
		APMATERNO VARCHAR(50),
		BORRADO BIT,
		FECHAMOD DATETIME
		);
CREATE TABLE PLANES (
		IDPLAN INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		DESCRIPCION VARCHAR(50),
		FECHAMOD DATETIME
);

CREATE TABLE COBERTURA (
		IDCOBERTURA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		DESCRIPCION VARCHAR(50),
		FECHAMOD DATETIME
);

CREATE TABLE REL_CLIENTE_PLAN(
	IDCP INT  IDENTITY(1,1) NOT NULL PRIMARY KEY,
	IDCLIENTE INT NOT NULL  FOREIGN KEY REFERENCES CLIENTES(IDCLIENTE) ON DELETE CASCADE ,
	IDPLAN INT NOT NULL  FOREIGN KEY REFERENCES PLANES(IDPLAN) ON DELETE CASCADE 
);


CREATE TABLE REL_PLAN_COBER(
	IDpc INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	IDPLAN INT NOT NULL  FOREIGN KEY REFERENCES PLANES(IDPLAN) ON DELETE CASCADE ,
	IDCOBER INT NOT NULL  FOREIGN KEY REFERENCES COBERTURA(IDCOBERTURA) ON DELETE CASCADE 
);

