CREATE OR ALTER PROCEDURE SP_ALTA_CLIENTE( 
	 @NOMBRE varchar(50),
	 @APPATER varchar(50),
	 @APMATER varchar(50)
	 )
AS
BEGIN
	INSERT  INTO CLIENTES(IDCLIENTE,NOMBRE,APPATERNO,APMATERNO,BORRADO) 
	VALUES ((SELECT ISNULL((SELECT MAX(IDCLIENTE) FROM CLIENTES),0)+1),@NOMBRE,@APPATER,@APMATER,0);
END;